# Generated by Django 3.2.5 on 2022-07-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
