# Generated by Django 3.2.5 on 2022-07-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
