# Generated by Django 3.2.5 on 2022-07-20 00:15

from django.db import migrations

def create_banner_obj(apps, schema_editor):
    Banner = apps.get_model('api', 'Banner')
    if len(Banner.objects.all()) == 0:
        banner = Banner()
        banner.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banner_bannerimage'),
    ]

    operations = [
        migrations.RunPython(create_banner_obj),
    ]
