# Generated by Django 3.2.5 on 2022-07-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bannerimage_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.banner', verbose_name=''),
        ),
    ]
