# Generated by Django 3.2.5 on 2022-07-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bannerimage_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product'),
        ),
    ]
